# Generated by Django 3.2.4 on 2021-06-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocalls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=500)),
                ('usefullness', models.CharField(max_length=1000)),
            ],
        ),
    ]
