# Generated by Django 3.2.4 on 2021-06-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocalls', '0002_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='usefullness_rating',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='usefullness',
            field=models.CharField(max_length=500),
        ),
    ]
