# Generated by Django 3.2.3 on 2021-05-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tablets', '0003_auto_20210516_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancetablet',
            name='store',
        ),
    ]
