# Generated by Django 3.2.3 on 2021-05-29 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tablets', '0004_remove_attendancetablet_store'),
        ('point_of_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetablet',
            name='point_of_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='point_of_sales.pointofsale'),
        ),
    ]
