# Generated by Django 3.1 on 2020-08-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=120)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
