# Generated by Django 3.1 on 2020-08-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=120)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('thread_id', models.IntegerField()),
            ],
        ),
    ]
