# Generated by Django 3.2.3 on 2021-05-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(default='Anonymous', max_length=120),
        ),
        migrations.AlterField(
            model_name='thread',
            name='username',
            field=models.CharField(default='Anonymous', max_length=120),
        ),
    ]
